# Generated by Django 4.2 on 2026-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อร้านค้า')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='ลิงก์ร้านค้า (Deep Link)')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x_twitter', 'X (Twitter)')], max_length=50, verbose_name='แพลตฟอร์ม')),
                ('status', models.CharField(choices=[('safe', 'ปลอดภัย (สีเขียว)'), ('pending', 'กำลังรอยืนยัน (สีเหลือง)'), ('scam', 'มิจฉาชีพ (สีแดง)')], default='pending', max_length=20, verbose_name='สถานะความน่าเชื่อถือ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มข้อมูล')),
            ],
        ),
    ]
