# Generated by Django 6.1 on 2026-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายร้านค้า'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='รูปร้านค้า'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('safe', 'ปลอดภัย (สีเขียว)'), ('pending', 'กำลังตรวจสอบ (สีเหลือง)'), ('scam', 'ควรระวัง (สีแดง)')], default='pending', max_length=20, verbose_name='สถานะความน่าเชื่อถือ'),
        ),
    ]
