# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('shop_name', 'ชื่อร้านค้า'), ('shop_link', 'ลิงก์ร้านค้า'), ('bank_account', 'เลขบัญชี'), ('account_owner', 'ชื่อเจ้าของบัญชี')], max_length=30)),
                ('identifier', models.CharField(max_length=500)),
                ('normalized_identifier', models.CharField(db_index=True, editable=False, max_length=500)),
                ('status', models.CharField(choices=[('safe', 'ปลอดภัย'), ('pending', 'กำลังตรวจสอบ'), ('scam', 'ควรระวัง')], default='pending', max_length=20)),
                ('source_name', models.CharField(default='ผู้ดูแลระบบ', max_length=255)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='riskrecord',
            constraint=models.UniqueConstraint(fields=('identifier_type', 'normalized_identifier'), name='unique_risk_record_identifier'),
        ),
    ]