# Generated by Django 6.1 on 2026-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_riskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskrecord',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('safe', 'ปลอดภัย (สีเขียว)'), ('pending', 'กำลังตรวจสอบ (สีเหลือง)'), ('scam', 'มิจฉาชีพ (สีแดง)')], default='pending', max_length=20, verbose_name='สถานะความน่าเชื่อถือ'),
        ),
    ]
