# Generated by Django 6.1 on 2026-10-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_riskrecord_evidence_image_alter_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='shops.riskrecord')),
            ],
        ),
    ]
