# Generated by Django 6.1 on 2026-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_type',
            field=models.CharField(choices=[('shop', 'ไปยังร้านค้า'), ('website', 'ไปยังเว็บไซต์'), ('none', 'ไม่แสดงปุ่ม')], default='shop', max_length=10),
        ),
    ]
