"""
Django settings for backend_api project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# โค้ดลับสำหรับบังคับให้ Django รุ่นใหม่ ทำงานกับฐานข้อมูล XAMPP รุ่นเก่าได้
import django.db.backends.base.base
import django.db.backends.mysql.features
django.db.backends.base.base.BaseDatabaseWrapper.check_database_version_supported = lambda self: True
django.db.backends.mysql.features.DatabaseFeatures.can_return_columns_from_insert = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-gwv$g#0g41e)zjsr&4t9g2rq$=i*=p3$ir-yu14ahdj7oe6y&&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # ยอมรับทุก Host ในโหมด Deploy ฟรี


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # เพิ่ม whitenoise สำหรับจัดการไฟล์ static ใน production
    'django.contrib.staticfiles',
    'shops',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # เพิ่ม whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'mysql://root:@127.0.0.1:3306/hiuhiu_db'),
        conn_max_age=600,
    ),
    'local_mysql': dj_database_url.parse('mysql://root:@127.0.0.1:3306/hiuhiu_db')
}



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# อนุญาตให้ทุกหน้าเว็บสามารถดึง API ได้ 
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# ตั้งค่า Cookie ให้ข้ามโดเมนได้ (จำเป็นสำหรับ Vercel -> Render)
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    'https://project-hiu-hiu.vercel.app',
    'http://127.0.0.1:3000',
    'http://localhost:3000',
]

# ตั้งค่า Search API
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')
SEARCH_ENGINE_ID = os.getenv('SEARCH_ENGINE_ID', '')
RISK_SEARCH_PROVIDER = os.getenv('RISK_SEARCH_PROVIDER', 'serper').strip().lower()
BRAVE_SEARCH_API_KEY = os.getenv('BRAVE_SEARCH_API_KEY', '')
SERPER_API_KEY = os.getenv('SERPER_API_KEY', '')

# ตั้งค่าสำหรับจัดการไฟล์รูปภาพที่อัปโหลด
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'